databaseChangeLog:
  - include:
      file: 001_create_table_event.yaml
      relativeToChangelogFile: true
  - include:
      file: 002_create_table_category.yaml
      relativeToChangelogFile: true
  - include:
      file: 003_create_table_participant.yaml
      relativeToChangelogFile: true
  - include:
      file: 004_create_table_party.yaml
      relativeToChangelogFile: true
  - include:
      file: 005_create_FK_category_event.yaml
      relativeToChangelogFile: true
  - include:
      file: 006_create_FK_party_event.yaml.yaml
      relativeToChangelogFile: true
  - include:
      file: 007_create_FK_party_participant.yaml
      relativeToChangelogFile: true
  - include:
      file: testdata/001_Category_test.yaml
      relativeToChangelogFile: true
  - include:
      file: testdata/002_Event_test.yaml
      relativeToChangelogFile: true
  - include:
      file: testdata/003_Participant_test.yaml
      relativeToChangelogFile: true
  - include:
      file: testdata/004_Party_test.yaml
      relativeToChangelogFile: true

