spring:
  datasource:
    url: jdbc:mysql://localhost:3306/device_rent
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asdf
  jpa:
    show-sql: true
    sql:
      init:
        mode: always

